import { REGISTER_USER_MUTATION, LOGIN_USER_MUTATION } from './userSchema';
import { CREATE_TEAM_MUTATION, GET_ALL_TEAMS } from './teamSchema'
import { GET_ALL_CHANNELS_BY_TEAM_ID } from './channelSchema';
export {
    REGISTER_USER_MUTATION,
    LOGIN_USER_MUTATION,
    CREATE_TEAM_MUTATION,
    GET_ALL_CHANNELS_BY_TEAM_ID,
    GET_ALL_TEAMS
};